version: '3.8'

networks:
  network_app:
    external: true

services:
  wa_backend:
    build:
      context: .
    container_name: wa_backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    volumes:
      - ./sessions:/sessions
      - ./logs:/logs
    restart: unless-stopped
    networks:
      - network_app
